<ul class="menu">
	<li n:if="$useHomepage">
		{if $homepage->isCurrent}
		<span class="active"><strong>{$homepage->label}</strong></span>
		{else}
		<a href="{$homepage->url}">{$homepage->label}</a>
		{/if}
	</li>

	{block #menu}
	<li n:foreach="$children as $item">
		{if $item->isCurrent}
		<span class="active"><strong>{$item->label}</strong></span>
		{else}
                    {if $item->isPublished}
                        <a href="{$item->url}" class="isPublished">{$item->label}</a>
                    {else}
                        <a href="{$item->url}" class="isNotPublished">{$item->label}</a>
                    {/if}
		{/if}
		
		{if $renderChildren && count($item->getComponents()) > 0}
		<ul>
			{include #menu, children => $item->getComponents()}
		</ul>
		{/if}
	</li>
	{/block}
</ul>
