<?php

header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 300'); // 5 minutes in seconds

?>
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name=robots content=noindex>
<meta name=generator content='Nette Framework'>

<style>
        body { font-size: 13px; font-family: Arial, sans-serif; background-color: #ffffff; background-image: url("../images/b.jpg"); background-repeat: no-repeat; line-height:1.5; height: 100%; }        
        #wrapper { min-height: 100%; height: auto !important; height: 100%; margin: 0 auto 0px; }
        .container { margin-left: auto; margin-right: auto; width: 920px; }
        #header { width: auto; font-size: 11px; background-color: #0099CC; padding: 3px 0px 3px 0px; color: #eee; border-bottom: 1px solid #003366; }
        #header a { color: #eee; text-decoration: none; }
        #header a:hover { text-decoration: underline; }
        #header span { color: #eee; }
        .grid_header_l { display: inline; float: left; margin-left: 50px; margin-top: 40px; }
        .grid_header_r { display: inline; float: right; margin-right: 10px; width: 600px; padding-left: 40px; }
        #main { margin-top: 10px; margin-bottom: 5px;}
        #main #content { margin-top: 51px; margin-bottom: 27px; min-height: 510px; background: #FFFFFF; -moz-border-radius: 4px; -webkit-border-radius: 4px; border-radius: 4px; -moz-box-shadow: rgba(200,200,200,1) 0 4px 18px; -webkit-box-shadow: rgba(200,200,200,1) 0 4px 18px; box-shadow: rgba(200,200,200,1) 0 4px 18px; }
        .grid_content { display: inline; float: left; margin-left: 10px; margin-right: auto; width: 900px }
        .grid_content_l { display: inline; float: left; margin-left: 10px; }
        #log_logo_holder { padding: 10px; padding-top: 25px; }
        #log_notifier_holder { font-size: 200%; padding:10px; color: #003366; margin-left: 10px; width: 840px; background-color: #E4F4F5; -moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 5px; }
        #log_text_wrapper { font-size: 100%; padding-top: 30px; float: left;}        
        .clear { clear: both; display: block; overflow: hidden; visibility: hidden; width: 0; height:0; }
</style>

<title>MUDRweb.cz - Stránka je dočasně nedostupná z důvodu údržby</title>

<div id="wrapper">

    <div id="main" class="container">
        <div class="grid_content">                                                                        
            <div id="content">   
                <div class="grid_content_l">
                    <div id="log_logo_holder">
                        <a href="http://mudrweb.cz"><img src="../images/logo.png" class="noborder" alt="Návrat na hlavní stránku mudrweb.cz" /></a>
                    </div>
                    <div id="log_notifier_holder">
                        Omlouváme se
                    </div>
                    <div id="log_text_wrapper">
                        <div class="grid_header_l">
                            <img src="../images/maintenance_red.png" alt="Probíhá údržba - mudrweb.cz" />
                        </div>        
                        <div class="grid_header_r">
                            <p>Stránka je dočasně nedostupná z důvodu údržby. Zkuste to prosím 
                                později. 
                                <br /><br />
                                V případě přetrvávajících problémů se obraťte na naši podporu - support@mudrweb.cz.
                                <br /><br />
                                Váš MUDRweb tým.
                            </p>
                        </div>   
                        <div class="clear">&nbsp;</div>
                    </div>       
                </div>
            </div>
        </div>
    </div>

</div>
    
<?php

exit;
